export const REPORT_FORM_CLEAN = "REPORT_FORM/CLEAN";
export const REPORT_FORM_IMAGE_LOADING = "REPORT_FORM/IMAGE_LOADING";
export const REPORT_FORM_IMAGE_ERROR = "REPORT_FORM/IMAGE_ERROR";
export const REPORT_FORM_IMAGE_RESIZED = "REPORT_FORM/IMAGE_RESIZED";
export const REPORT_FORM_IMAGE_LOADED = "REPORT_FORM/IMAGE_LOADED";
export const REPORT_FORM_DATETIME = "REPORT_FORM/DATETIME";
export const REPORT_FORM_CATEGORY = "REPORT_FORM/CATEGORY";
export const REPORT_FORM_ADDRESS_LOADING = "REPORT_FORM/ADDRESS_LOADING";
export const REPORT_FORM_ADDRESS_LOADED = "REPORT_FORM/ADDRESS_LOADED";
export const REPORT_FORM_ADDRESS_ERROR = "REPORT_FORM/ADDRESS_ERROR";
export const REPORT_FORM_SET_COORDS = "REPORT_FORM/SET_COORDS";

export const REPORT_APP_LOADED = "REPORT_APP/LOADED";
export const REPORT_APP_LOADING = "REPORT_APP/LOADING";
