export const FETCH_USER_LOADING = "FETCH_USER/LOADING";
export const FETCH_USER_ERROR = "FETCH_USER/ERROR";
export const FETCH_USER_SUCCESS = "FETCH_USER/SUCCESS";
export const FETCH_USER_EMPTY = "FETCH_USER/EMPTY";
export const FETCH_USER_LOGOUT = "FETCH_USER/LOGOUT";
export const UPDATE_USER_LOADING = "UPDATE_USER/LOADING";
export const UPDATE_USER_SUCCESS = "UPDATE_USER/SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER/FAILED";
