export const ROUTES = {
  home: "/",
  epuap: "/epuap",
  faq: "/faq",
  gallery: "/galeria",
  mandate: "/mandat",
  privavyPolicy: "/polityka-prywatnosci",
  project: "/projekt",
  regulations: "/przepisy",
  websiteRegulations: "/regulamin",
  stats: "/statystyki",
  statusCheck: "/zapytaj-o-status",
  install: "/aplikacja",
  changelog: "/changelog",
  publicInfoAccess: "/dostep-do-informacji-publicznej",
  report: "/zgloszenie",
  login: "/logowanie",
  newReport: "/nowe-zgloszenie",
  user: {
    main: "/uzytkownik",
    home: "/",
    reports: "zgloszenia",
    edit: "edit",
  },
  userReports: "/uzytkownik/zgloszenia",
  userEdit: "/uzytkownik/edit",
  shipment: "/wysylka",
  notFound: "/404",
  maintenance: "/maintenance",
  adminGallery: "/adm-gallery",
};
