name: CI

on:
  push:
    branches: [ "master", "main", "deploy-staging-cicd" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 16
    - name: Check
      run: |
        yarn
        yarn lint
        yarn tsc
    - name: Create config
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
    - name: Build
      run: yarn build:prod
  deploy:
    if: github.ref == 'refs/heads/deploy-staging-cicd'
    runs-on: ubuntu-latest
    environment: staging
    needs: [build]
    steps:
    - name: Deploy to staging
      uses: nogsantos/scp-deploy@master
      with:
        src: ./dist/*
        host: ${{ secrets.SCP_HOST }}
        remote: /var/www/staging.uprzejmiedonosze.net/new/
        port: ${{ secrets.SCP_PORT }}
        user: github
        key: ${{ secrets.ID_ED25519 }}
