name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 16
    - name: Check
      run: |
        yarn
        yarn lint
        yarn tsc
    - name: Create config
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
    - name: Build
      run: yarn build:prod
    - name: Deploy to staging
      if: github.ref == 'refs/heads/master'
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.ID_ED25519 }}" > ~/.ssh/id_ed25519
        chmod 700 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.SCP_HOST }} >> ~/.ssh/known_hosts
        scp -i ~/.ssh/id_ed25519 -v -o StrictHostKeyChecking=no -P ${{ secrets.SCP_PORT }} -r ./dist/* github@${{ secrets.SCP_HOST }}:/var/www/staging.uprzejmiedonosze.net/new/

